### ISSUE TITLE
yaml 有文本块的模式，使用起来会清爽很多

### ISSUE THREAD

**Issue by noear** [ty-wssf/solon-rminf#1]
### 关于 yaml 文本块
 
 * 没有使用文本块

```yaml
id: "d1"
layout:
  - task: "System.out.println(\"hello world!\");"
```

 * 使用文本块，很适合写脚本（这是 yaml 特性，你那个 description 也可以这样）

```yaml
id: "d1"
layout:
  - task: |
       System.out.println("hello world!");
```

### 另外 solon-flow 现在还出了可视化的设计器：

https://solon.noear.org/article/1065
